#!/bin/python

import urllib.request, json

city = "Columbus"
api_key = "2ab607d5eea916b958b7b06382b08c40"
units = "Kelvin"
unit_key = "K"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q=Columbus,us&appid=2ab607d5eea916b958b7b06382b08c40".format(city, api_key, units)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]))

print("%s, %i °%s" % (info, temp, unit_key))
